version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network

  php:
    image: php:8-fpm
    volumes:
      - ./laravel:/var/www/html
    networks:
      - laravel_network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sign_project
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel_network
    command: sh -c "npm install && docker-php-entrypoint php-fpm"

  # crond:
  #  image: your_custom_cron_image
  #  volumes:
  #    - ./cron:/etc/cron.d
  #  depends_on:
  #    - laravel
  #  networks:
  #    - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data: